<!DOCTYPE html>
<html>
<head>
    <title>Vue.JS </title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </head>
    <body>
    <div id ="app">
      <ul>
        <li v-for="item in items">{{ item}}</li>
        </ul>
         <input id="input" type="text" v-model="newitem">
         <button v-on:click="addition">Add to do Item</button>
         
        </div>
        var app= new Vue{{
        el:'#app',
        data : {
        items :['add milk', 'add sugar' , 'add tea powder', 'add vanila']
        },
        methods:{
        addItem() {
        this.items.push(this.newItem);
        this.newItem = '';
        }
        }
